### ISSUE TITLE
Handle leak when dealing with PSP ISO files (possibly with Japanese text)

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#249] opened 2020-09-04 15:27 UTC
Having a issue where rom-properties will hold a handle to PSP ISO even if no property boxes are open, possibly if the filename contains Japanese text, though I'm not sure about that part

Examples of the filenames
セブンスドラゴン２０２０-Ⅱ [NPJH50716]
セブンスドラゴン２０２０ [NPJH50459]
ＡＫＩＢＡ’Ｓ　ＴＲＩＰ　ＰＬＵＳ [NPJH50563] * don't know if it copied correctly, but the original filename is all wide-chars
Aedis Eclipse - Generation of Chaos [NPEH00106] * not sure what's causing this one as its the only one that isn't japanese

**Comment by GerbilSoft** [comment] 2020-09-04 16:36
Can't seem to reproduce this with git master.

**Comment by Masamune3210** [comment] 2020-09-04 17:26
Ok, ill test it a bit more later tonight or tomorrow and see if i can find anything more

**Comment by GerbilSoft** [comment] 2020-09-04 21:40
PSP isn't supported by rom-properties yet (though I started a branch locally), so this would be in the plain old ISO parser.

I might release a v1.6.2 soon because of the PS1/PS2 handle leak issues. If you can definitively reproduce this with the latest build from master, post the ISO filename and MD5.

**Comment by Masamune3210** [comment] 2020-09-04 22:32
Will do

**Comment by Masamune3210** [comment] 2020-09-06 00:54
Still happens, even redownloaded the file straight from the PSN servers to make sure it wasnt a corrupted copy. As soon as I un-register rom-properties.dll and restart explorer, I can do whatever I want with the file. The minute I register the dll and look at the file, locks are aquired 

== File: 'F:\NPS Downloads\pspemu\ISO\ＡＫＩＢＡ’Ｓ　ＴＲＩＰ　ＰＬＵＳ [NPJH50563].iso'
-- ISO-9660 Disc Image detected
System ID:          'PSP GAME'
Volume ID:          'AKB_STRP_PLUS'
Volume Size:        '835.3 MiB'
Volume Set:         'AKB_STRP_PLUS'
Publisher:          'ACQUIRE'
Data Preparer:      'ACQUIRE'
Application:        'PSP GAME'
Copyright File:     ''
Abstract File:      ''
Bibliographic File: ''
Creation Time:      03/19/12 02:08:57
Modification Time:  Unknown
Expiration Time:    Unknown
Effective Time:     Unknown

MD5:        2BED6FCCD4FACB08B385094FC3C3A3D3

**Comment by GerbilSoft** [comment] 2020-09-06 01:35
What is the build of rom-properties.dll that's registered in the system? (View the file's properties, then check the Version tab.)

**Comment by Masamune3210** [comment] 2020-09-06 01:39
I'm assuming this is what you are talking about
![image](https://user-images.githubusercontent.com/1053504/92316330-e6e45a00-efb7-11ea-8ad5-150b2bd5886d.png)

**Comment by GerbilSoft** [comment] 2020-09-06 01:42
That indicates you're using the latest in the feature/rpcli-in-main-dll branch. I'll check this ISO image again in both master and the feature branch and see if I can reproduce it.

**Comment by Masamune3210** [comment] 2020-09-06 01:43
Let me know if you want me to test anything, i just grabbed one from appveyor, was unaware it wasnt from master lol

**Comment by GerbilSoft** [comment] 2020-09-06 01:51
Reproduced it on master. It seems that "Unlocker" isn't finding which process is holding it open, but I can't move the file anyway.

**Comment by Masamune3210** [comment] 2020-09-06 01:51
yeah, the only way I could see the handle was by using resource monitor and searching for the file path

**Comment by GerbilSoft** [comment] 2020-09-06 02:32
AppVeyor build: https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/35050723

I found a few instances where the IDiscReader object wasn't being properly released in IsoPartition and XDVDFSPartition. XDVDFSPartition is used by XboxDisc, which is used by RomDataFactory when trying to determine if an ISO image is actually a game console disc image instead of just a plain old ISO image.

With the above commit, the PSP ISO is no longer locked when rom-properties is registered.

**Comment by Masamune3210** [comment] 2020-09-06 02:34
Will try it and let you know once its done building

**Comment by GerbilSoft** [comment] 2020-09-06 03:08
I need to pay more attention to valgrind's output and turn on full leak check.

Running rpcli with this disc image before this patch:
```
==403890== HEAP SUMMARY:
==403890==     in use at exit: 21,566 bytes in 135 blocks
==403890==   total heap usage: 482 allocs, 347 frees, 908,540 bytes allocated
==403890== 
==403890== LEAK SUMMARY:
==403890==    definitely lost: 96 bytes in 2 blocks
==403890==    indirectly lost: 8,860 bytes in 13 blocks
==403890==      possibly lost: 0 bytes in 0 blocks
==403890==    still reachable: 12,610 bytes in 120 blocks
==403890==         suppressed: 0 bytes in 0 blocks
==403890== Rerun with --leak-check=full to see details of leaked memory
```

After this patch:
```
==404471== HEAP SUMMARY:
==404471==     in use at exit: 12,138 bytes in 119 blocks
==404471==   total heap usage: 339 allocs, 220 frees, 423,253 bytes allocated
==404471== 
==404471== LEAK SUMMARY:
==404471==    definitely lost: 0 bytes in 0 blocks
==404471==    indirectly lost: 0 bytes in 0 blocks
==404471==      possibly lost: 0 bytes in 0 blocks
==404471==    still reachable: 12,138 bytes in 119 blocks
==404471==         suppressed: 0 bytes in 0 blocks
==404471== Rerun with --leak-check=full to see details of leaked memory
```

EDIT: The "before" output was actually from the feature/PSP-ISO branch. From master, before the patch:
```
==408020== HEAP SUMMARY:
==408020==     in use at exit: 12,830 bytes in 124 blocks
==408020==   total heap usage: 339 allocs, 215 frees, 423,253 bytes allocated
==408020== 
==408020== LEAK SUMMARY:
==408020==    definitely lost: 48 bytes in 1 blocks
==408020==    indirectly lost: 172 bytes in 3 blocks
==408020==      possibly lost: 0 bytes in 0 blocks
==408020==    still reachable: 12,610 bytes in 120 blocks
==408020==         suppressed: 0 bytes in 0 blocks
==408020== Rerun with --leak-check=full to see details of leaked memory
```

There might be a memory leak in feature/PSP-ISO that needs fixing.

**Comment by Masamune3210** [comment] 2020-09-06 03:10
Seems to check out, I can rename and delete the file perfectly even with the dll registered! So the patch is functioning at least
Valgrind seems useful, need to take a look at it one of these days.

**Comment by GerbilSoft** [comment] 2020-09-06 03:10
Closing since this is verified as fixed.

**Closed as completed by GerbilSoft** 2020-09-06 03:10 UTC
Labels: bug, FIXED
