### ISSUE TITLE
rp-config does not save settings and keys in Manjaro Gnome

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#369] opened 2022-10-21 21:37 UTC
rp-config does not save settings and keys in Manjaro Gnome (keys.conf and rom-properties.conf files are not created).
Manually creating keys.conf and rom-properties.conf files shows the settings and keys, but any changes you make are not saved.

**Comment by GerbilSoft** [comment] 2022-10-21 22:33
Duplicate of #368.

**Closed as not planned by GerbilSoft** 2022-10-21 22:33 UTC
Labels: duplicate

**Comment by Amnesia1000** [comment] 2022-10-21 22:35
The two issues were closed
