### ISSUE TITLE
CHD image support for PS1

### ISSUE THREAD

**Issue by DankRank** [GerbilSoft/rom-properties#375] opened 2023-01-03 14:28 UTC
CHD is a disc compression format that was originated by MAME, and has since became somewhat popular to use with PS1 discs. Duckstation supports it, for example.

To create a CHD, use chdman which is part of mame (mame-tools package on debian and arch): 
`chdman createcd -i game.cue -o game.chd`
Alternatively, you can find redump sets in chd format online.

References:
- https://github.com/mamedev/mame
- https://github.com/rtissera/libchdr (recommended lib)
- https://github.com/stenzek/duckstation/blob/master/src/util/cd_image_chd.cpp (libchdr example usage)

Since it's not PS1 specific, CHD support could benefit from disc image abstractions mentioned in #322. Also note that CHD is not just a CD compression format, it also supports laserdiscs, hard disks and "raw" images.

**Comment by Masamune3210** [comment] 2023-01-04 00:16
#161

**Comment by GerbilSoft** [comment] 2023-01-04 00:35
Closing because it's a duplicate of #161, which is still planned for "sometime", along with the disc image abstraction stuff.

**Closed as not planned by GerbilSoft** 2023-01-04 00:35 UTC
Labels: duplicate, enhancement
