### ISSUE TITLE
PS2 bin/cue combo causing possible crash?

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#247] opened 2020-08-21 03:35 UTC
Is there any way to somehow disable any processing of a certain file type? I am having a issue where explorer will crash any time i enter a folder with a Playstation 2 bin/cue style cd game, and the only thing I can figure is maybe its an issue with the plugin, as far as I know nothing else is messing with them

**Comment by GerbilSoft** [comment] 2020-08-21 03:43
Per-file extension registration isn't currently supported at the moment.

Can you try to narrow down which file is causing the crash? You can use the `rpcli` command line tool on each file in the directory to figure it out. Once you've narrowed it down, post the filename and MD5, and I'll take a look.

**Comment by Masamune3210** [comment] 2020-08-21 04:01
Ok, will have to do that tomorrow as I just went to bed. If it helps at all I can tell you the exact game I got it with, it's super busy a move from the archive.org archives

**Comment by Masamune3210** [comment] 2020-08-21 04:01
I can get the exact md5 tomorrow if needed

**Comment by GerbilSoft** [comment] 2020-08-24 01:20
It's possible that there's a handle leak, but as far as I know, all handles are closed when not viewing properties and/or after thumbnails are processed. I'll double-check this.

EDIT: Reproduced here on Win7/64 here.

**Comment by Masamune3210** [comment] 2020-09-02 14:21
any chance you have a build with the handle bug fixed? would build myself but dev env isnt currently able to be set up

**Comment by GerbilSoft** [comment] 2020-09-03 16:25
Release builds for Windows are available here: https://ci.appveyor.com/project/GerbilSoft/rom-properties/history

**Comment by Masamune3210** [comment] 2020-09-03 17:08
Alright, thanks! Wasn't sure if it was being regularly built anywhere

**Comment by GerbilSoft** [comment] 2020-09-13 04:10
Closing since this is fixed.

**Closed as completed by GerbilSoft** 2020-09-13 04:10 UTC
Labels: bug, FIXED
