### ISSUE TITLE
[Windows] PS1/PS2 Images Crashing File Pickers

### ISSUE THREAD

**Issue by TwilightSlick** [GerbilSoft/rom-properties#259] opened 2020-09-22 22:19 UTC
When I load up some applications that use a Windows Explorer file picker window (most notably Imgburn) and I navigate it to a folder containing a PS1 or PS2 disc image, the application instantly crashes.

This bug occurred back in 1.6 as well, and only is triggered when loading a PlayStation disc image.
Other applications that are affected include the EPSXE emulator.

This is also somewhat related to issue #258 in which Windows Explorer crashes when loading certain PS1 disc images.
Both bugs occur in the current 1.7.1 release.

**Comment by GerbilSoft** [comment] 2020-09-24 13:48
It's the same component, so it's the same underlying issue.

Duplicate of: #258 [Windows] Explorer crash when trying to load certain PS1 images

**Closed as not planned by GerbilSoft** 2020-09-24 13:48 UTC
Labels: bug, duplicate
