### ISSUE TITLE
Use Existing Filetype Icons If No Icon Or Thumbnail Exists

### ISSUE THREAD

**Issue by TheKins** [GerbilSoft/rom-properties#319] opened 2021-09-02 10:13 UTC
Because I'm a huge nerd, I like to use [Default Programs Editor](https://defaultprogramseditor.com/) to apply icons to certain ROM filetypes. I installed rom-properties on my Windows 10 x64 machine in order to get the internal icons for DS etc. with external images disabled, only to find that the icons for certain ROM file formats are now completely stomped into being a generic Windows "blank sheet" icon. My NES and FDS files are unaffected, but SNES, GB/C, etc. all are. Attempting to re-set the icons using Default Programs Editor doesn't seem to work.

![image](https://user-images.githubusercontent.com/2977232/131825973-f4e53361-ceea-4ea7-96d2-1302c0b51654.png)

Is this a bug or intended behavior, and if it's the latter, is there anything I can do to work around it?

Thanks.

EDIT: This also seems to effect my Sublime Text file formats, for some reason, so I guess this could be a duplicate of #318?
EDIT EDIT: Uninstalling rom-properties does not help - the intended icons are visible in Default Programs Editor, but not in Explorer. Clearing the icon cache and restarting my PC has not helped. What on Earth?

**Comment by GerbilSoft** [comment] 2021-09-02 14:30
This is definitely a bug, and it indicates that rom-properties' "fallback" mechanism isn't working. I will test this out over the weekend to see what's going on.

What version of Windows are you using?

**Comment by TheKins** [comment] 2021-09-02 14:34
Windows 10 Home x64 Version 21H1.

**Comment by GerbilSoft** [comment] 2021-09-02 16:48
Regarding why some are affected but others aren't: .nes files aren't affected because the only ROM Properties handler that registers that extension is the NES handler, and it doesn't support thumbnails at the moment.

.bin is registered by multiple different handlers, some of which support thumbnails.
.gb and .smc also support thumbnails using the external RPDB online title screen database. I suspect that it might not be an issue with fallbacks per se, but that RPDB either doesn't have those title screens or rp-download isn't working. (...or you have external images disabled, as I just noticed in your first post)

It *should* fall back to the default icons if the download fails, but if it doesn't, that'd explain the problem.

**Comment by GerbilSoft** [comment] 2021-09-02 17:04
Tested this on Windows 7, and icon fallbacks seem to work correctly.

Will test on Windows 10 later today.

**Comment by GerbilSoft** [comment] 2021-09-02 18:12
> Uninstalling rom-properties does not help - the intended icons are visible in Default Programs Editor, but not in Explorer. Clearing the icon cache and restarting my PC has not helped. What on Earth?

It seems Default Programs Editor does something weird with the file associations. If you set e.g. .gb files to open with Notepad, then regsvr32 rom-properties.dll, the icon disappears, but regsvr32 /u rom-properties.dll and it reappears. Not so with whatever Default Programs Editor is doing.

I'll get to the first part (regular Windows file associations), then do some more thorough debugging with DPE.

**Comment by TheKins** [comment] 2021-09-02 22:53
Oh, interesting. Is there a "right" way to apply icon properties to file-types that I should be using instead?

**Comment by Masamune3210** [comment] 2021-09-02 23:15
It's more that DPE is probably doing something incorrectly or is leaving some garbage behind that is likely messing things up. I'm not sure of any tools for handling this myself but I would be careful with what you try as it involves the registry which if messed up too bad can cause major issues

**Comment by GerbilSoft** [comment] 2021-09-03 01:06
I haven't adjusted for DPE yet, but I started a branch that intentionally does not modify any custom application registrations in `HKCR\Applications`. This is where Windows 8+ puts custom associations when you manually assign a program to a specific filetype. ROM Properties was editing this, but it seemed to be doing it incorrectly (and unregistration didn't always work), so it resulted in issues.

With these changes, the small icon will always be the associated program, but thumbnail view will show the RPDB preview (with the program icon in the bottom right corner).

Test build: https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/40630143

NOTE: You may have to run `regsvr32 /u rom-properties.dll` on the old version at least twice before registering the new version.

**Comment by GerbilSoft** [comment] 2021-09-03 01:18
For what it's worth, I tested setting a custom icon with DPE for .gb files. With these changes, "example.gb" (a Game Boy ROM with a garbage title that doesn't exist on RPDB), it shows the custom icon, whereas a copy of Tetris shows the Tetris title screen with a Notepad icon on the bottom right. (I associated it with Notepad because I don't have a Game Boy emulator installed on my Win10 VM.)

A copy of the Tetris ROM with a .gbc extension also shows the title screen, but no program icon, since .gbc isn't associated with anything.

Unregistering rom-properties.dll results in the .gb files showing the custom icon, and .gbc showing a blank icon.

**Comment by TheKins** [comment] 2021-09-03 01:32
Minor Update: Looks like I can "fix" my busted custom icons for file formats by changing the program they're associated to in Windows, then pointing them back to the program I actually want to use in DPE. Weird. I guess the file association got all funky?

**Comment by GerbilSoft** [comment] 2021-09-03 01:35
Windows file associations are all sorts of screwy. Among other things, starting with Windows 8, MS added a hash to user program selections to prevent malicious programs from hijacking e.g. the default browser.

On Linux systems, programs merely indicate what file types they support in the .desktop file, and the desktop environment handles the rest. No need to mess with a registry.

Icons are standardized as well. They're located in /usr/share/icons, categorized by theme and category, and named after the MIME type.

For thumbnailing, there's DE-specific stuff, but it only has to be done once, and it's located in a single file rather than having to edit an existing set of files.

**Comment by TheKins** [comment] 2021-09-03 02:03
Just tried the test build linked an hour ago. Stomps icons again, but not as many, and doesn't prevent them from being re-set like the current stable seemingly does. Progress!

**Comment by GerbilSoft** [comment] 2021-09-03 02:14
Which icons are still not working?

**Comment by TheKins** [comment] 2021-09-03 02:16
It reset Gameboy, SNES and Genesis (BIN/MD) icons, IIRC. I was able to change them back, though.

**Comment by GerbilSoft** [comment] 2021-09-03 02:16
If you reset the icons with DPE, then re-register rom-properties, do they get clobbered? Before-and-after screenshots would be appreciated. (I tested this locally with Game Boy [.gb] and it seemed to work fine.)

**Comment by TheKins** [comment] 2021-09-03 02:25
It seems like uninstalling rom-properties via the provided installer damaged the associations into no longer displaying icons.

File Association w/ Icon, No Rom-Properties:
![image](https://user-images.githubusercontent.com/2977232/131941035-142cca71-8ef5-4dc0-81f5-1f755191df1f.png)

After Uninstalling Rom-Properties:
![image](https://user-images.githubusercontent.com/2977232/131941159-bd57a4be-b04b-4b6d-82fa-33bf49b4a244.png)

EDIT: Interestingly, reinstalling rom-properties seems to "repair" the damage and make re-set icons visible again. Odd.

**Comment by GerbilSoft** [comment] 2021-09-03 02:32
I can't seem to add an icon for .bin files without associating it with a program. Did you have to associate .bin files with a program before it showed up in DPE, and if so, what program?

**Comment by TheKins** [comment] 2021-09-03 02:35
I associated it with an emulator, specifically Bizhawk. Typically for multi-format emulators like Bizhawk, I end up giving each platform its own association to a dummy program then edit that to point to Bizhawk so everything has its own icon and description. (EDIT: This was a hangover from when I used RetroArch and every platform needed its own command line arguments to load the proper core, if it seems like a weird way of doing stuff!) I hope that's not what's breaking everything, but I can't see how.

**Comment by GerbilSoft** [comment] 2021-09-03 02:41
Tested it with BizHawk associated and I can't reproduce the brokenness when unregistering rom-properties.dll.

Can you export the following keys from the registry:
* `HKEY_CLASSES_ROOT\.bin`
* `HKEY_CLASSES_ROOT\bin_auto_file`
* `HKEY_CLASSES_ROOT\Applications\EmuHawk.exe` (or whatever the name of the program you have it associated with is)

Do note that the resulting .reg files may have your user profile name in them, so I'd recommend redacting it before posting.

EDIT: You may also need to clear the thumbnail cache. rp-config's Thumbnail Cache tab provides a convenient button to do this.

**Comment by TheKins** [comment] 2021-09-03 03:00
[bin.txt](https://github.com/GerbilSoft/rom-properties/files/7103026/bin.txt)
[bin_auto_file.txt](https://github.com/GerbilSoft/rom-properties/files/7103027/bin_auto_file.txt)
[binexe.txt](https://github.com/GerbilSoft/rom-properties/files/7103028/binexe.txt)

I'm hoping these help at least figure out what kind of unholy mess I've turned my file associations into. At the least things currently work _now_.

**Comment by GerbilSoft** [comment] 2021-09-03 03:02
`HKEY_CLASSES_ROOT\Applications\bin.exe` looks like it's messed up from a previous rom-properties registration. Delete that entire key (bin.exe), then re-associate the .bin files with BizHawk (or bin.exe) and see if that helps.

EDIT: .bin is associated with EmuHawk.exe, not bin.exe. Not sure what that entry is from. You might want to try deleting the `HKEY_CLASSES_ROOT\Applications\EmuHawk.exe` entry as well.

**Comment by TheKins** [comment] 2021-09-03 03:43
Hmm. Looking at my registry, at this point I might just have to assume that some of my emulator file associations are just a unique kind of messed up and have no bearing on how other users may be effected by most of this :V

**Comment by GerbilSoft** [comment] 2021-09-03 03:45
Regardless, I'll probably add something to the registration functionality tomorrow to go through `HKCR\Applications` and remove any rom-properties leftovers, then merge that to master and maybe release v1.8.4.

**Comment by GerbilSoft** [comment] 2021-11-09 15:37
Closing as fixed for 1.9.

EDIT: rom-properties leftovers removal was implemented in commit 47475c2a45dbd8af9f3feac69a63ad4eead9407d for `HKCR\Applications`.

**Closed as completed by GerbilSoft** 2021-11-09 15:37 UTC
Labels: bug, FIXED
