### ISSUE TITLE
"The action can't be completed because the file is open in Windows Explorer" when renaming/deleting ISO

### ISSUE THREAD

**Issue by ghost** [GerbilSoft/rom-properties#256] opened 2020-09-17 16:10 UTC
This bug occurrs on v1.6.1 and causes to lock some ISO files from being modified, renamed, deleted or moved.

Trying to delete an ISO file shows an error as that file is "in use" by another process.
![2020-09-17_17-01-22_explorer](https://user-images.githubusercontent.com/29345291/93496972-c9908380-f907-11ea-9b87-d04d60b752ed.png)

This affects
- PS2 ISO
- PS3 ISO
- Windows 10 ISO
- Linux distro ISO

This doesn't affect
- PSP ISO
- GameCube ISO
- Wii ISO
- Xbox 360 ISO

Killing both explorer.exe and COM Surrogate (dllhost.exe) processes then deleting the affected ISO file via CMD is a temporary solution, uninstalling RP seems to get rid of the error but comes back when installing it again.

Tested on clean install of Windows 10 and Windows 8.1 in VM's.

**Comment by GerbilSoft** [comment] 2020-09-17 21:22
Known issue; will be fixed in v1.7, which I plan to release over the weekend.

Duplicate of #247 and #249.

**Closed as not planned by GerbilSoft** 2020-09-17 21:22 UTC
Labels: bug, duplicate
