### ISSUE TITLE
[Feature Request] Gamecube Cover

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#240] opened 2020-07-13 15:22 UTC
The current way that Gamecube game images are displayed is with the banner, but this is aesthetically very ugly, is there a chance it will show the box cover?

Or it could also be used to cover the disc

I could use the image database at https://www.gametdb.com/ (I don't know if it's possible, but for giving some kind of solution)

**Comment by GerbilSoft** [comment] 2020-07-13 15:24
Cover art is an option. Use rp-config to specify whether to use boxart or banner.

**Comment by Amnesia1000** [comment] 2020-07-13 15:32
I have the following configuration in the rom-properties.conf file
GameCube = ExtCover
But it still shows the banner

Another question, download all Wii covers (wii and gamecube) and 3DS covers from gametdb. By unzipping the covers I realize that the 3ds cover folder is called coversM, should the name change it to covers or leave it like this?

Also, the folder structure is correct?
"/home/amnesia/.cache/rom-properties/3ds/coverM/US/XXXXXX.png"
"/home/amnesia/.cache/rom-properties/wii/cover/US/XXXXXX.png"

Likewise, the external covers are still not shown.

**Comment by GerbilSoft** [comment] 2020-07-13 16:23
External covers not showing up is likely caused by the same problem as #239.

**Comment by Amnesia1000** [comment] 2020-07-16 14:55
But that problem is not caused by the failure of the image download? Here I am talking about the images already downloaded and placed in the cache folder of rom-properties.

**Comment by GerbilSoft** [comment] 2020-07-17 22:55
Closing this as a duplicate of #239.

The problem is caused by bubblewrap.

**Closed as not planned** 2020-09-18 01:26 UTC
Labels: bug, duplicate
