### ISSUE TITLE
Update COMPILING.md with arch support

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#306] opened 2021-04-12 17:43 UTC
The dependencies in quotes cannot be found (maybe it has another name or they are contained in another package) 

```
All: curl zlib libpng libjpeg-turbo nettle pkgconf tinyxml2 libbsd gettext libseccomp
Optional decompression: zstd lz4 lzo
KDE 4.x: "libqt4-dev" kdelibs
KDE 5.0: qt5-base qt5-tools extra-cmake-modules kio kwidgetsaddons kfilemetadata
XFCE (GTK+ 2.x): glib2 gtk2 gdk-pixbuf2 "libthunarx-2-dev" libcanberra 
XFCE (GTK+ 3.x): glib2 gtk3 cairo "libthunarx-3-dev" libcanberra
GNOME, MATE, Cinnamon: glib2 gtk3 cairo libnautilus-extension libcanberra
```

**Comment by GerbilSoft** [comment] 2021-04-14 01:45
Duplicate of PR #307.

**Closed as not planned by GerbilSoft** 2021-04-14 01:45 UTC
Labels: duplicate, enhancement
