### ISSUE TITLE
File extension exclusion

### ISSUE THREAD

**Issue by SaraJLeen** [GerbilSoft/rom-properties#201] opened 2019-10-26 16:16 UTC
At current rom-properties registers for every file extension it can handle with no exceptions. It would really help to have a configuration dialog for toggling these on/off, though even an exclusion list for initial extension registration would really help!

**Comment by GerbilSoft** [comment] 2020-06-23 17:28
Duplicate of #21: Add ability to disable specific features to the config file

**Closed as not planned** 2023-08-13 16:50 UTC
Labels: duplicate
